# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CoOpManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CoOpManager
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'

  target 'CoOpManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
